# DON'T REMOVE THIS FILE.
# This file is for render site varibles and plugins
#
# The actual configuration files are stored in the `config/_default/` folder.


######################### site variables ##############################
# customize your color and font from here.
[params.variables]
color_primary = "#F12639"
color_secondary = "#1F2749"
body_color = "#fff"
text_color = "#1a1e2c"
text_light = "#8b8f9c"
text_dark = "#222222"
border_color = "#f2f2f2"
black = "#000"
white = "#fff" 
light = "#f5f5f5"

# font variables
# base font size for full website, 
font_size = "16px" # default is 16px

# Font Scale Sizes
# "minorSecond": 1.067,
# "majorSecond": 1.125,
# "minorThird": 1.2,
# "majorThird": 1.25, 
# "perfectFourth": 1.333,
# "augmentedFourth": 1.414,
# "perfectFifth": 1.5,
# "goldenRatio": 1.618
font_scale = "1.205" # default is "majorThird": 1.25

# go to https://fonts.google.com/ to find the font you want to use. select your font and copy only the bold part from the URL. and paste it here.
# example: "Work+Sans:wght@400;500;600"
font_primary = "Oswald:wght@400;500;600"
font_primary_type = "sans-serif"            # [serif/sans-serif]
font_secondary = "Roboto:wght@400"
font_secondary_type = "sans-serif"                    # [serif/sans-serif]
font_icon = "themify"           # https://themify.me/themify-icons


############################# Plugins ##############################

# CSS Plugins 
[[params.plugins.css]]
link = "plugins/themify-icons/icons.css"
[[params.plugins.css]]
link = "plugins/swiper/swiper-bundle.css"  
[[params.plugins.css]]
link = "plugins/glightbox/glightbox.min.css" 

# JS Plugins
# [[params.plugins.js]]
# link = "plugins/jquery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/cookie.js"
[[params.plugins.js]]
link = "plugins/lazy-loader.js"
[[params.plugins.js]]
link = "plugins/shuffle/shuffle.min.js" 
[[params.plugins.js]]
link = "plugins/swiper/swiper-bundle.js"
[[params.plugins.js]]
link = "plugins/webfont/webfont-loader-2.js"
[[params.plugins.js]]
link = "plugins/glightbox/glightbox.min.js" 
attributes = "async"
